### ISSUE TITLE
Project Specifications

### ISSUE THREAD

**Issue by chacha** [Team3128/AttendanceScanner#1]
We need to identify the main requirements our team needs in the app for us to start using it, and then implement a plan for making them happen. Think of like a 'need' vs 'want' list. And then we can start working on it.

**Comment by multiplemonomials** [comment]
Alright, here's what I already implemented:
- ability to scan ID cards and store the times in a database.
- screen for setting the names of students
- screen for viewing attendance by day

**Comment by multiplemonomials** [comment]
And, if I remember, you wanted me to add: 
- way to view the total hours a person attended (in a particular time span? Should it be a separate screen, or on the attendance view?)
- require mentor password for certian features (exactly what functions would require this password?)
