### ISSUE TITLE
Some Barcodes Read Incorrectly

### ISSUE THREAD

**Issue by chacha** [Team3128/AttendanceScanner#2]
Several Student IDs are read incorrectly and result in much longer numbers. This seems to be an issue with the scanner itself. I'll post examples soon.

**Comment by chacha** [comment]
I need to get the original number, but it generates some numbers like 305401097, which is not a valid student ID.

**Comment by chacha** [comment]
The nice thing is that they consistently sign in and out the same, so we can just map them to names and be done with it.

**Comment by multiplemonomials** [comment]
We can test this further by checking if an internet-generated barcode with the same student ID is also misread.   It could be some kind of issue with the barcodes on the cards.

**Comment by multiplemonomials** [comment]
OK, so a workaround is to generate a Code 93 barcode with the same text and tape it to the back of their student ID.  This is definitely a barcode scanner problem, not an app one, so I don't want to add some kind of software workaround just for this.
